apiVersion: skaffold/v2beta25
kind: Config
metadata:
  name: minizinc-dispatcher
build:
  artifacts:
  - image: mzn-dispatcher
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - mzn-dispatcher.yaml
